### PR TITLE
uploaded tree height and binary tree code for basic learning.

### PR DESCRIPTION
**Pull request by Stormchaser1o1**

### CODE REVIEW

**Comment by Ankitcoder54** [comment]
Code is not working, Try to submit it again after code works.

**Comment by Stormchaser1o1** [comment]
bro then please just inform me why making it as spam.

**Comment by Stormchaser1o1** [comment]
please revert it.

**Comment by Ankitcoder54** [comment]
Done it after getting correct code

**Comment by Stormchaser1o1** [comment]
have uploaded the code now check and revert this spam, as I will not be able to participate in the event bro.

**Comment by Stormchaser1o1** [comment]
abe sun bhank kk lund karna hai tho kar jyada dimag mat kharab kar. github chala aata nahi hai bc aa gya apni maa chudane. mc jab koi code run nahi hota tho samne vale ko bolte hai bhai apna code change karke de de but nahi tujhe tho apne gaand marani hai naa, tu spam marega. mar li spam aab maa chudale jaa di kk lund.

**Comment by Stormchaser1o1** [comment]
are bhai suun tu bhaout slow hai, rahne de.. code run karana aata nahi hai bewakoof ko noob. sun isko agar revert karna hai tho kar vagra apni gaand mara. aur mujhe contibutors se bhi hata bc mai aise noob ki repo ka contributor nahi banana chata gaandu. bhak bsdke.

**Pull request merged**
